# Generated by Django 5.2.7 on 2025-10-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='Cliente',
            new_name='cliente',
        ),
    ]
