# Generated by Django 5.2.7 on 2025-10-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_cliente_cita_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('razon', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
