# Generated by Django 5.2.7 on 2025-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cita_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana (0=Lunes, 6=Domingo)', unique=True)),
                ('activo', models.BooleanField(default=True, help_text='¿Se atiende este día?')),
                ('hora_apertura', models.TimeField(default='10:00', help_text='Hora de inicio de atención')),
                ('hora_cierre', models.TimeField(default='19:00', help_text='Hora de fin de atención')),
            ],
            options={
                'verbose_name': 'Configuración de Horario',
                'verbose_name_plural': 'Configuración de Horarios',
                'ordering': ['dia_semana'],
            },
        ),
    ]
